---
title: "writing_functions"
author: "Jennifer Lee"
date: "2022-10-31"
output: html_document
---

```{r setup}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
echo = TRUE,
warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Z-scores!!

Let's compute the z-score version of a list of numbers.
```{r}
x_vec = rnorm(25, mean = 7, sd = 4)

(x_vec - mean(x_vec)) / sd(x_vec)
```

Suppose you want to do this often.

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Z scores only work for numbers")
  }
  
  if (length(x) < 3) {
    stop("Z scores only really work if you have three or more numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  
  z
}
```

```{r}
z_scores(x = x_vec)
z_scores(x = rbinom(1000, 1, .6))
```

## Let's have multiple outputs

```{r}

```

